language: java
script: cd geronimo-javamail_1.4 && mvn clean package
env:
  - MAVEN_OPTS="-Dfile.encoding=UTF-8"
  - MAVEN_OPTS="-Dfile-encoding=ISO-8859-1"
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

